/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      typography: (theme) => ({
        DEFAULT: {
          css: {
            maxWidth: "100%",
            color: "inherit",
            strong: {
              color: "inherit", // This ensures bold text inherits the proper color
              fontWeight: "600",
            },
            a: {
              color: theme("colors.blue.500"),
              "&:hover": {
                color: theme("colors.blue.600"),
              },
              textDecoration: "none",
              borderBottom: `1px solid ${theme("colors.blue.500")}`,
              transition: "all 0.2s ease-in-out",
            },
            h1: {
              color: "inherit",
              fontSize: "2.25em",
              fontWeight: "800",
              lineHeight: "1.3",
              letterSpacing: "-0.025em",
              marginTop: "2.5em",
              marginBottom: "1em",
            },
            h2: {
              color: "inherit",
              fontSize: "1.875em",
              fontWeight: "700",
              lineHeight: "1.35",
              letterSpacing: "-0.02em",
              marginTop: "2em",
              marginBottom: "1em",
            },
            h3: {
              color: "inherit",
              fontSize: "1.5em",
              fontWeight: "600",
              lineHeight: "1.4",
              marginTop: "1.75em",
              marginBottom: "0.75em",
            },
            h4: {
              color: "inherit",
              fontSize: "1.25em",
              fontWeight: "600",
              lineHeight: "1.4",
              marginTop: "1.5em",
              marginBottom: "0.75em",
            },
            p: {
              color: "inherit",
              marginTop: "1.25em",
              marginBottom: "1.25em",
              lineHeight: "1.8",
            },
            ul: {
              marginTop: "1.25em",
              marginBottom: "1.25em",
              paddingLeft: "1.625em",
              listStyleType: "disc",
              li: {
                marginTop: "0.5em",
                marginBottom: "0.5em",
                "&::marker": {
                  color: theme("colors.gray.400"),
                },
              },
            },
            ol: {
              marginTop: "1.25em",
              marginBottom: "1.25em",
              paddingLeft: "1.625em",
              li: {
                marginTop: "0.5em",
                marginBottom: "0.5em",
                "&::marker": {
                  color: theme("colors.gray.500"),
                  fontWeight: "600",
                },
              },
            },
            "ul ul, ul ol, ol ul, ol ol": {
              marginTop: "0.75em",
              marginBottom: "0.75em",
            },
            blockquote: {
              fontWeight: "500",
              fontStyle: "italic",
              color: "inherit",
              borderLeftWidth: "0.25rem",
              borderLeftColor: theme("colors.gray.300"),
              quotes: '"\\201C""\\201D""\\2018""\\2019"',
              marginTop: "1.6em",
              marginBottom: "1.6em",
              paddingLeft: "1em",
            },
            code: {
              color: theme("colors.pink.500"),
              backgroundColor: theme("colors.gray.100"),
              paddingLeft: "0.5rem",
              paddingRight: "0.5rem",
              paddingTop: "0.25rem",
              paddingBottom: "0.25rem",
              borderRadius: "0.375rem",
              fontSize: "0.875em",
              fontWeight: "600",
              "&::before": {
                content: '""',
              },
              "&::after": {
                content: '""',
              },
            },
            "code::before": {
              content: '""',
            },
            "code::after": {
              content: '""',
            },
            pre: {
              color: theme("colors.gray.200"),
              backgroundColor: theme("colors.gray.800"),
              overflowX: "auto",
              fontWeight: "400",
              fontSize: "0.875em",
              lineHeight: "1.7142857",
              marginTop: "1.7142857em",
              marginBottom: "1.7142857em",
              borderRadius: "0.375rem",
              paddingTop: "0.8571429em",
              paddingRight: "1.1428571em",
              paddingBottom: "0.8571429em",
              paddingLeft: "1.1428571em",
            },
            "pre code": {
              backgroundColor: "transparent",
              borderWidth: "0",
              borderRadius: "0",
              padding: "0",
              fontWeight: "400",
              color: "inherit",
              fontSize: "inherit",
              fontFamily: "inherit",
              lineHeight: "inherit",
            },
            table: {
              width: "100%",
              tableLayout: "auto",
              textAlign: "left",
              marginTop: "2em",
              marginBottom: "2em",
              fontSize: "0.875em",
            },
            thead: {
              color: "inherit",
              borderBottomWidth: "1px",
              borderBottomColor: theme("colors.gray.300"),
            },
            "thead th": {
              verticalAlign: "bottom",
              paddingRight: "0.5714286em",
              paddingBottom: "0.5714286em",
              paddingLeft: "0.5714286em",
              fontWeight: "600",
            },
            "tbody tr": {
              borderBottomWidth: "1px",
              borderBottomColor: theme("colors.gray.200"),
            },
            "tbody tr:last-child": {
              borderBottomWidth: "0",
            },
            "tbody td": {
              verticalAlign: "baseline",
              paddingTop: "0.5714286em",
              paddingRight: "0.5714286em",
              paddingBottom: "0.5714286em",
              paddingLeft: "0.5714286em",
            },
            img: {
              marginTop: "2em",
              marginBottom: "2em",
              borderRadius: "0.375rem",
            },
            hr: {
              marginTop: "3em",
              marginBottom: "3em",
              borderColor: theme("colors.gray.200"),
            },
          },
        },
        invert: {
          css: {
            "--tw-prose-body": theme("colors.gray.300"),
            "--tw-prose-headings": theme("colors.white"),
            "--tw-prose-links": theme("colors.blue.400"),
            "--tw-prose-links-hover": theme("colors.blue.500"),
            "--tw-prose-underline": theme("colors.blue.400/0"),
            "--tw-prose-underline-hover": theme("colors.blue.400"),
            "--tw-prose-bold": theme("colors.gray.100"), // Updated to use a lighter color in dark mode
            "--tw-prose-counters": theme("colors.gray.400"),
            "--tw-prose-bullets": theme("colors.gray.400"),
            "--tw-prose-hr": theme("colors.gray.700"),
            "--tw-prose-quote-borders": theme("colors.gray.700"),
            "--tw-prose-captions": theme("colors.gray.400"),
            "--tw-prose-code": theme("colors.pink.400"),
            "--tw-prose-code-bg": theme("colors.gray.900"),
            "--tw-prose-pre-code": theme("colors.gray.200"),
            "--tw-prose-pre-bg": theme("colors.gray.800"),
            "--tw-prose-pre-border": "transparent",
            "--tw-prose-th-borders": theme("colors.gray.700"),
            "--tw-prose-td-borders": theme("colors.gray.700"),
            strong: {
              color: theme("colors.gray.100"), // Explicitly set bold text color in dark mode
            },
          },
        },
      }),
      fontFamily: {
        chakra: ["Chakra Petch", "serif"],
        arial: ["Arial", "sans-serif"],
        verdana: ["Verdana", "sans-serif"],
        georgia: ["Georgia", "serif"],
        tahoma: ["Tahoma", "sans-serif"],
        courier: ["Courier New", "monospace"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
